---
title: "GSE149758 Control Animals (all cell types)"
author: "Noah Siegel"
date: "`r format(Sys.time(), '%d %B, %Y, %H:%M')`"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "results") })
output: html_document
---

```{r message = FALSE, warning = FALSE, results = "hide", echo = FALSE}
source("R/main.r")
```

```{r message = FALSE, warning = FALSE, results = "hide", echo = FALSE}
int <- readRDS(file.path(getwd(), "output/rdata/2021_November_08_14:56_azimuth_input.rds"))
n3 <- AddAzimuthResults(int, filename = file.path(getwd(), 'output/rdata/azimuth_results.Rds'))

n3@meta.data$sex <- ifelse( n3@meta.data$orig.ident == "control_2",
                            "Female","Male")
n3$celltype.sex <- paste(n3$sex, n3$predicted.annotation.l1, sep = "_")
Idents(n3) <- "celltype.sex"
mac <- n3
```

```{r message = FALSE, warning = FALSE, results = "hide", echo = FALSE}
# SCTransform
n3[["percent.mt"]] <- PercentageFeatureSet(n3, pattern = "^mt-")
n3 <- SCTransform(n3, vars.to.regress = "percent.mt", verbose = FALSE)
# Standard visualization and clustering workflow
n3 <- FindVariableFeatures(n3)
n3 <- ScaleData(n3)
n3 <- RunPCA(n3, npcs = 30, verbose = FALSE)
# t-SNE and Clustering
n3 <- RunUMAP(n3, reduction = "pca", dims = 1:20)
n3 <- FindNeighbors(n3, reduction = "pca", dims = 1:20)
n3 <- FindClusters(n3, resolution = 0.5)
```

```{r echo=FALSE}
p <- DimPlot(n3, reduction = "umap", group.by = "orig.ident", label = F) &
  theme(text = element_text(),
        axis.text.x=element_text(angle=45, hjust=1, size=20),
        axis.title = element_text(size=20),
        axis.title.y.right = element_text(size = 20),
        legend.text=element_text(size=20),
        legend.title=element_text(size=20),
        axis.line = element_line(size=1.1))
p
ggsave(file=file.path("output", "results", "3n",
                  paste("grouped", ".png", sep="")), plot=p, width=14, height=8, dpi=600)
```

```{r echo=FALSE}
p <- DimPlot(n3, reduction = "umap", group.by = "sex",
             cols = c("pink", "lightblue"), label = F) &
  theme(text = element_text(),
        axis.text.x=element_text(angle=45, hjust=1, size=20),
        axis.title = element_text(size=20),
        axis.title.y.right = element_text(size = 20),
        legend.text=element_text(size=20),
        legend.title=element_text(size=20),
        axis.line = element_line(size=1.1))
p
ggsave(file=file.path("output", "results", "3n",
                  paste("sex", ".png", sep="")), plot=p, width=10, height=8, dpi=600)
```

```{r echo = FALSE}
p <- DimPlot(n3, reduction = "umap", group.by = "predicted.annotation.l1", label = T) &
  theme(text = element_text(),
        axis.text.x=element_text(angle=45, hjust=1, size=20),
        axis.title = element_text(size=20),
        axis.title.y.right = element_text(size = 20),
        legend.text=element_text(size=20),
        legend.title=element_text(size=20),
        axis.line = element_line(size=1.1))
p
ggsave(file=file.path("output", "results", "3n",
                  paste("cell-types_assigned", ".png", sep="")), plot=p, width=14, height=8, dpi=600)
```

## ADAMDEC1 EXpression
```{r echo=FALSE}
p = FeaturePlot(object = n3, 
            features = c("ADAMDEC1"),
            cols = c("grey", "blue"),
            reduction  = "umap") &
  theme(text = element_text(),
        axis.text.x=element_text(angle=45, hjust=1, size=20),
        axis.title = element_text(size=20),
        axis.title.y.right = element_text(size = 20),
        legend.text=element_text(size=20),
        legend.title=element_text(size=20),
        axis.line = element_line(size=1.1))
p
ggsave(file=file.path("output", "results", "3n",
                  paste("ADAMDEC1", ".png", sep="")), plot=p, width=14, height=8, dpi=600)
```

```{r echo=FALSE}
p <- VlnPlot(n3, features = "ADAMDEC1", group.by = c("orig.ident"), assay = "RNA", log=T, combine = T) &
  theme(text = element_text(),
        axis.text.x=element_text(angle=45, hjust=1, size=20),
        axis.title = element_text(size=20),
        axis.title.y.right = element_text(size = 20),
        legend.text=element_text(size=20),
        legend.title=element_text(size=20),
        axis.line = element_line(size=1.1))
p
ggsave(file=file.path("output", "results", "3n",
                  paste("ADAMDEC1_group", ".png", sep="")), plot=p, width=10, height=8, dpi=600)
```

```{r echo=FALSE}
p <- VlnPlot(n3, features = "ADAMDEC1", group.by = c("predicted.annotation.l1"), 
             assay = "RNA", log=T, combine = T) &
  theme(text = element_text(),
        axis.text.x=element_text(angle=45, hjust=1, size=20),
        axis.title = element_text(size=20),
        axis.title.y.right = element_text(size = 20),
        legend.text=element_text(size=20),
        legend.title=element_text(size=20),
        axis.line = element_line(size=1.1)) + theme(legend.position = 'none')
p
ggsave(file=file.path("output", "results", "3n",
                  paste("ADAMDEC1_celltype", ".png", sep="")), plot=p, width=14, height=8, dpi=600)
```