---
title: "GSE149758 Control Animals"
author: "Noah Siegel"
date: "`r format(Sys.time(), '%d %B, %Y, %H:%M')`"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "documents") })
output: html_document
---

```{r}
source("R/main.r")
```

```{r}
int <- readRDS(file.path(getwd(), "output/rdata/2021_November_08_14:56_azimuth_input.rds"))
object <- AddAzimuthResults(int, filename = file.path(getwd(), 'output/rdata/azimuth_results.Rds'))

# SCTransform
object[["percent.mt"]] <- PercentageFeatureSet(object, pattern = "^mt-")
object <- SCTransform(object, vars.to.regress = "percent.mt", verbose = FALSE)
```

```{r}
# Standard visualization and clustering workflow
object <- FindVariableFeatures(object)
object <- ScaleData(object)
object <- RunPCA(object, npcs = 30, verbose = FALSE)
# t-SNE and Clustering
object <- RunUMAP(object, reduction = "pca", dims = 1:20)
object <- FindNeighbors(object, reduction = "pca", dims = 1:20)
object <- FindClusters(object, resolution = 0.5)
```

```{r}
p <- DimPlot(object, reduction = "umap", group.by = "orig.ident", label = F)
p
ggsave(file=file.path("output", "results", 
                  paste("grouped", ".png", sep="")), plot=p, width=15, height=18, dpi=600)
```

```{r}
p <- DimPlot(object, reduction = "umap", group.by = "predicted.annotation.l1", label = T)
p
ggsave(file=file.path("output", "results", 
                  paste("cell-types_assigned", ".png", sep="")), plot=p, width=15, height=18, dpi=600)
```

## ADAMDEC1 EXpression
```{r}
p = FeaturePlot(object = object, 
            features = c("ADAMDEC1"),
            cols = c("grey", "blue"),
            reduction  = "umap")
p
ggsave(file=file.path("output", "results", 
                  paste("ADAMDEC1", ".png", sep="")), plot=p, width=15, height=18, dpi=600)
```

```{r}
p <- VlnPlot(object, features = "ADAMDEC1", group.by = c("orig.ident"), assay = "RNA")
p
ggsave(file=file.path("output", "results", 
                  paste("ADAMDEC1_group", ".png", sep="")), plot=p, width=15, height=18, dpi=600)
```

```{r}
p <- VlnPlot(object, features = "ADAMDEC1", group.by = c("predicted.annotation.l1"), assay = "RNA")
p
ggsave(file=file.path("output", "results", 
                  paste("ADAMDEC1_celltype", ".png", sep="")), plot=p, width=15, height=18, dpi=600)
```


