---
title: "GSE149758 Control Animals (macrophages)"
author: "Noah Siegel"
date: "`r format(Sys.time(), '%d %B, %Y, %H:%M')`"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "results") })
output: html_document
---

```{r message = FALSE, warning = FALSE, results = "hide", echo = FALSE}
suppressPackageStartupMessages({
  library(sctransform)
  library(Seurat)
  library(patchwork)
  library(ggplot2)
  library(EnhancedVolcano)
  library(dplyr)
  library(kableExtra)
  library(xlsx)
})
```

```{r message = FALSE, warning = FALSE, results = "hide", echo = FALSE}
source('R/azimuth_grouped_input.r')
```

```{r echo=FALSE}
int <- readRDS(file.path(getwd(), "rdata/2023_Apr_25_18:23_azimuth_input.rds"))

# Download Azimuth human lung reference
# https://app.azimuth.hubmapconsortium.org/app/human-lung
n3 <- AddAzimuthResults(int,
                        filename = file.path(getwd(),
                                             'rdata/azimuth_results.Rds'))

n3@meta.data$sex <- ifelse( n3@meta.data$orig.ident == "control_2",
                            "Female","Male")
n3$celltype.sex <- paste(n3$sex, n3$predicted.annotation.l1, sep = "_")
Idents(n3) <- "celltype.sex"
mac <- n3
```

# All cell types

```{r message = FALSE, warning = FALSE, results = "hide", echo = FALSE}
# SCTransform
n3[["percent.mt"]] <- PercentageFeatureSet(n3, pattern = "^mt-")
n3 <- SCTransform(n3, vars.to.regress = "percent.mt", verbose = FALSE)
# Standard visualization and clustering workflow
n3 <- FindVariableFeatures(n3)
n3 <- ScaleData(n3)
n3 <- RunPCA(n3, npcs = 30, verbose = FALSE)
# t-SNE and Clustering
n3 <- RunUMAP(n3, reduction = "pca", dims = 1:20)
n3 <- FindNeighbors(n3, reduction = "pca", dims = 1:20)
n3 <- FindClusters(n3, resolution = 0.5)
```

```{r echo=FALSE}
p <- DimPlot(n3, reduction = "umap", group.by = "orig.ident", label = F) &
  theme(text = element_text(),
        axis.text.x=element_text(angle=45, hjust=1, size=20),
        axis.title = element_text(size=20),
        axis.title.y.right = element_text(size = 20),
        legend.text=element_text(size=20),
        legend.title=element_text(size=20),
        axis.line = element_line(size=1.1))
p
ggsave(file=file.path("results",
                  paste("grouped", ".png", sep="")), plot=p, width=14, height=8, dpi=600)
```

```{r echo=FALSE}
p <- DimPlot(n3, reduction = "umap", group.by = "sex",
             cols = c("pink", "lightblue"), label = F) &
  theme(text = element_text(),
        axis.text.x=element_text(angle=45, hjust=1, size=20),
        axis.title = element_text(size=20),
        axis.title.y.right = element_text(size = 20),
        legend.text=element_text(size=20),
        legend.title=element_text(size=20),
        axis.line = element_line(size=1.1))
p
ggsave(file=file.path("results",
                  paste("sex", ".png", sep="")), plot=p, width=10, height=8, dpi=600)
```

```{r echo = FALSE}
p <- DimPlot(n3, reduction = "umap", group.by = "predicted.annotation.l1", label = T) &
  theme(text = element_text(),
        axis.text.x=element_text(angle=45, hjust=1, size=20),
        axis.title = element_text(size=20),
        axis.title.y.right = element_text(size = 20),
        legend.text=element_text(size=20),
        legend.title=element_text(size=20),
        axis.line = element_line(size=1.1))
p
ggsave(file=file.path("results",
                  paste("cell-types_assigned", ".png", sep="")), plot=p, width=14, height=8, dpi=600)
```

## ADAMDEC1 EXpression
```{r echo=FALSE}
p = FeaturePlot(object = n3, 
            features = c("ADAMDEC1"),
            cols = c("grey", "blue"),
            reduction  = "umap") &
  theme(text = element_text(),
        axis.text.x=element_text(angle=45, hjust=1, size=20),
        axis.title = element_text(size=20),
        axis.title.y.right = element_text(size = 20),
        legend.text=element_text(size=20),
        legend.title=element_text(size=20),
        axis.line = element_line(size=1.1))
p
ggsave(file=file.path("results",
                  paste("ADAMDEC1", ".png", sep="")), plot=p, width=14, height=8, dpi=600)
```

```{r echo=FALSE}
p <- VlnPlot(n3, features = "ADAMDEC1", group.by = c("orig.ident"), assay = "RNA", log=T, combine = T) &
  theme(text = element_text(),
        axis.text.x=element_text(angle=45, hjust=1, size=20),
        axis.title = element_text(size=20),
        axis.title.y.right = element_text(size = 20),
        legend.text=element_text(size=20),
        legend.title=element_text(size=20),
        axis.line = element_line(size=1.1))
p
ggsave(file=file.path("results",
                  paste("ADAMDEC1_group", ".png", sep="")), plot=p, width=10, height=8, dpi=600)
```

```{r echo=FALSE}
p <- VlnPlot(n3, features = "ADAMDEC1", group.by = c("predicted.annotation.l1"), 
             assay = "RNA", log=T, combine = T) &
  theme(text = element_text(),
        axis.text.x=element_text(angle=45, hjust=1, size=15),
        axis.title = element_text(size=20),
        axis.title.y.right = element_text(size = 20),
        legend.text=element_text(size=20),
        legend.title=element_text(size=20),
        axis.line = element_line(size=1.1)) + theme(legend.position = 'none')
p
ggsave(file=file.path("results",
                  paste("ADAMDEC1_celltype", ".png", sep="")), plot=p, width=14, height=8, dpi=600)
```

# Macrophages

```{r}
mac <- subset(x = mac, subset = predicted.annotation.l1 == "Macrophage")
```

```{r message = FALSE, warning = FALSE, results = "hide"}
# SCTransform
mac[["percent.mt"]] <- PercentageFeatureSet(mac, pattern = "^mt-")
mac <- SCTransform(mac, vars.to.regress = "percent.mt", verbose = FALSE)
# Standard visualization and clustering workflow
mac <- FindVariableFeatures(mac)
mac <- ScaleData(mac)
mac <- RunPCA(mac, npcs = 30, verbose = FALSE)
# t-SNE and Clustering
mac <- RunUMAP(mac, reduction = "pca", dims = 1:20)
mac <- FindNeighbors(mac, reduction = "pca", dims = 1:20)
mac <- FindClusters(mac, resolution = 0.5)
```

```{r}
p <- DimPlot(mac, reduction = "umap", group.by = "orig.ident", label = F) &
  theme(text = element_text(),
        axis.text.x=element_text(angle=45, hjust=1, size=20),
        axis.title = element_text(size=20),
        axis.title.y.right = element_text(size = 20),
        legend.text=element_text(size=20),
        legend.title=element_text(size=20),
        axis.line = element_line(size=1.1))
p
ggsave(file=file.path("results",
                  paste("macrophage-group", ".png", sep="")), plot=p, width=14, height=8, dpi=600)
```

```{r}
p = FeaturePlot(object = mac, 
            features = c("ADAMDEC1"),
            cols = c("grey", "blue"),
            reduction  = "umap")&
  theme(text = element_text(),
        axis.text.x=element_text(angle=45, hjust=1, size=20),
        axis.title = element_text(size=20),
        axis.title.y.right = element_text(size = 20),
        legend.text=element_text(size=20),
        legend.title=element_text(size=20),
        axis.line = element_line(size=1.1))
p
ggsave(file=file.path("results",
                  paste("macrophage-ADAMDEC1", ".png", sep="")), plot=p, width=14, height=8, dpi=600)
p
```


```{r}
p <- DimPlot(mac, reduction = "umap", group.by = "sex",
             cols = c("pink", "lightblue"), label = F)&
  theme(text = element_text(),
        axis.text.x=element_text(angle=45, hjust=1, size=20),
        axis.title = element_text(size=20),
        axis.title.y.right = element_text(size = 20),
        legend.text=element_text(size=20),
        legend.title=element_text(size=20),
        axis.line = element_line(size=1.1))
p
ggsave(file=file.path("results",
                  paste("macrophage-sex", ".png", sep="")), plot=p, width=14, height=8, dpi=600)
```

```{r}
poscells <- WhichCells(mac, expression = ADAMDEC1 > 0)
mac$Macrophages<- ifelse(colnames(mac) %in% poscells, "ADAMDEC1+ Macrophage", "Conv. Macrophage")
```

```{r}
p <- DimPlot(mac, reduction = "umap", group.by = "Macrophages",
             cols = c("red", "blue"), label = F)&
  theme(text = element_text(),
        axis.text.x=element_text(angle=45, hjust=1, size=20),
        axis.title = element_text(size=20),
        axis.title.y.right = element_text(size = 20),
        legend.text=element_text(size=20),
        legend.title=element_text(size=20),
        axis.line = element_line(size=1.1))
p
ggsave(file=file.path("results",
                  paste("macrophage-types", ".png", sep="")), plot=p, width=14, height=8, dpi=600)
```
# Differential Gene Expresssion
## Macrophages
```{r message = FALSE, warning = FALSE, results = "hide", echo = FALSE}
new_idents <- RegroupIdents(mac, metadata = "Macrophages")
degs <- FindMarkers(new_idents, ident.1 = "ADAMDEC1+ Macrophage",
                    ident.2 = "Conv. Macrophage", group.by="Macrophages")
top.DEG <- head(degs, 10)
top.DEG <- row.names(top.DEG)
```

```{r}
p <- EnhancedVolcano(degs,
  lab = rownames(degs),
  x = 'avg_log2FC',
  y = 'p_val_adj',
  selectLab = top.DEG,
  xlab = bquote('Average fold change'),
  pCutoff = 10e-14,
  pointSize = 2.0,
  labSize = 3.0,
  labCol = 'black',
  labFace = 'bold',
  boxedLabels = TRUE,
  colAlpha = 4/5,
  legendPosition = 'right',
  colGradient = c('red3', 'royalblue'),
  legendLabSize = 14,
  legendIconSize = 4.0,
  drawConnectors = TRUE,
  widthConnectors = 1.0,
  colConnectors = 'black',
  title = "Macrophages",
  subtitle = "Differential expression")+
 coord_cartesian(clip = "off")
p
```

```{r}
kable(degs, booktabs = T, caption = "", digits = 3,
      format.args = list(scientific = FALSE)) %>%
  kable_styling(latex_options = "striped")  %>%
  kable_styling(position = "left") %>%
  kable_styling(font_size = 10)
```

```{r}
path <-  file.path("results", "macrophage-degs")
```

```{r}
# export CSV of DEGS
write.csv(degs, paste(path, ".csv", sep = ""), quote = F)
```

## Sex
```{r message = FALSE, warning = FALSE, results = "hide", echo = FALSE}
new_idents <- RegroupIdents(mac, metadata = "sex")
degs <- FindMarkers(new_idents, ident.1 = "Male",
                    ident.2 = "Female", group.by="sex")
top.DEG <- head(degs, 10)
top.DEG <- row.names(top.DEG)
```

```{r}
p <- EnhancedVolcano(degs,
  lab = rownames(degs),
  x = 'avg_log2FC',
  y = 'p_val_adj',
  selectLab = top.DEG,
  xlab = bquote('Average fold change'),
  pCutoff = 10e-14,
  pointSize = 2.0,
  labSize = 3.0,
  labCol = 'black',
  labFace = 'bold',
  boxedLabels = TRUE,
  colAlpha = 4/5,
  legendPosition = 'right',
  colGradient = c('red3', 'royalblue'),
  legendLabSize = 14,
  legendIconSize = 4.0,
  drawConnectors = TRUE,
  widthConnectors = 1.0,
  colConnectors = 'black',
  title = "Sex",
  subtitle = "Differential expression")+
 coord_cartesian(clip = "off")
p
```

```{r}
kable(degs, booktabs = T, caption = "", digits = 3,
      format.args = list(scientific = FALSE)) %>%
  kable_styling(latex_options = "striped")  %>%
  kable_styling(position = "left") %>%
  kable_styling(font_size = 10)
```

```{r}
path <-  file.path("results", "sex-degs")
```

```{r}
# export CSV of DEGS
write.csv(degs, paste(path, ".csv", sep = ""), quote = F)
```

## Interecting genes between Conv. vs ADAMDEC1 & Male vs. Female
```{r}
sex <- read.delim('results/sex-degs.csv', sep = ',') %>%
  rename(`Sex DEGs` = X)

mac <- read.delim('results/macrophage-degs.csv', sep = ',') %>%
  rename(`Macrophage DEGs` = X)

# DEGs present in sex comparison by absent in macrophage comparison
unique_to_sex <- sex %>%
  anti_join(mac, by = c('Sex DEGs' = 'Macrophage DEGs')) 

# DEGs present in macrophage comparison by absent in sex comparison
unique_to_mac <- mac %>%
  anti_join(sex, by = c('Macrophage DEGs' = 'Sex DEGs'))

# DEGs present in both comparisons
shared_both <- mac %>%
  inner_join(sex, by = c('Macrophage DEGs' = 'Sex DEGs'))
```


```{r}
require(openxlsx)
wb <- createWorkbook()

# Add sheets to workbook
addWorksheet(wb, "Male vs. Female")
addWorksheet(wb, "Conv. vs. ADAMDEC1")
addWorksheet(wb, "DEGs unique to sex comparison")
addWorksheet(wb, "DEGs unique to mac comparison")
addWorksheet(wb, "DEGs shared in both comparisons")

# Write data to each sheet
writeData(wb, "Male vs. Female", sex)
writeData(wb, "Conv. vs. ADAMDEC1", mac)
writeData(wb, "DEGs unique to sex comparison", unique_to_sex)
writeData(wb, "DEGs unique to mac comparison", unique_to_mac)
writeData(wb, "DEGs shared in both comparisons", shared_both)

# Save workbook
saveWorkbook(wb, file.path("results" ,"degs.xlsx"))
```

## HALLMARK genes

```{r}
require(escape)
require(dittoSeq)
require(SingleCellExperiment)
hallmark <- suppressMessages(UpdateSeuratObject(mac))
sce <- as.SingleCellExperiment(hallmark)
GS <- getGeneSets(species = "Homo sapiens", library = "H")
```

```{r include=F}
gsea_path <- Sys.glob(file.path(getwd(), "rdata", "*gsea.RData"))
if (identical(gsea_path, character(0))){
  
  ES <- enrichIt(obj = hallmark, gene.sets = GS, groups = 1000, cores = 4)
  # 4 cores works on my 32Gb  computer (2021-11-10)

  out_file <- file.path(getwd(), "rdata", paste(format(Sys.time(),
                       '%Y_%B_%d_%H:%M'), "gsea.RData", sep = "_"))
  saveRDS(object = ES, file = out_file)

} else   readRDS(file.path(getwd(), "rdata", "*gsea.RData"))

```

```{r}
scgsea <- AddMetaData(hallmark, ES)
met.data <- merge(colData(sce), ES, by = "row.names", all=TRUE)
row.names(met.data) <- met.data$Row.names
met.data$Row.names <- NULL
colData(sce) <- met.data
```

```{r cache=F}
p <- dittoHeatmap(scgsea, genes = NULL, metas = names(ES), 
             annot.by = c("Macrophages"),
             order.by = c("sex"),
             fontsize = 7, 
             cluster_cols = TRUE)
path=file.path("results", "HALLMARK",
               paste("gsea-macrophage", ".png",  sep = ""))
p
ggsave(file = path, plot = p, width=14, height=8, dpi=600)
```

```{r cache=F}
p <- dittoHeatmap(scgsea, genes = NULL, metas = names(ES), 
             annot.by = c("sex"),
             order.by = c("sex"),
             fontsize = 7, 
             cluster_cols = TRUE)
path=file.path("results", "HALLMARK",
               paste("gsea-sex", ".png",  sep = ""))
p
ggsave(file = path, plot = p, width=14, height=8, dpi=600)
```

```{r}
require(stringr)
require(data.table)
df = t(scgsea@meta.data)
names = row.names(df)
names = as.data.frame(names)
HALLMARK = names[(names$names) %like% "HALLMARK_", ]
for (i in HALLMARK){
  p = multi_dittoPlot(sce, vars = i, 
                group.by = "Macrophages", plots = c( "vlnplot", "boxplot"), 
                ylab = "Enrichment Scores", 
                theme = theme_classic() + theme(text = element_text(size=20)))
  
path=file.path("results", "HALLMARK",
               paste("escape-output_",i,".png",  sep = ""))
    image <- p
    ggsave(file = path, plot = image, width=14, height=8, dpi=600)
  p
}
```